control_tf_planner:
  _target_: nuplan_garage.planning.simulation.planner.control_tf_planner.control_tf_planner.ControlTFPlanner
  _convert_: 'all'

  map_radius: 300 # Radius to consider around ego [m]
  thread_safe: true
  checkpoint_path: /data/t4p/checkpoints/GPTS_SKP_loss1_K1_data1_SgFix/training_results/checkpoint-378000 # Path to checkpoint file
