
NUM_OF_ATTN_NEIGHBORS: 16
NUM_INPUT_ATTR_AGENT: 29
NUM_INPUT_ATTR_MAP: 9

NUM_CHANNEL_IN_MLP_AGENT: 256
NUM_CHANNEL_IN_MLP_MAP: 64
NUM_LAYER_IN_MLP_AGENT: 3
NUM_LAYER_IN_MLP_MAP: 5
NUM_LAYER_IN_PRE_MLP_MAP: 3

D_MODEL: 256
NUM_ATTN_LAYERS: 6
NUM_ATTN_HEAD: 8 
DROPOUT_OF_ATTN: 0.1 

USE_LOCAL_ATTN: True

PROPOSAL_PATH: "/home/ldr/workspace/StateTransformer/data/waymo/cluster_64_center_dict.pkl"