CONTEXT_ENCODER:
    NAME: MTREncoder

    NUM_OF_ATTN_NEIGHBORS: 16
    NUM_INPUT_ATTR_AGENT: 29
    NUM_INPUT_ATTR_MAP: 2
    
    NUM_CHANNEL_IN_MLP_AGENT: 64
    NUM_CHANNEL_IN_MLP_MAP: 64
    NUM_LAYER_IN_MLP_AGENT: 2
    NUM_LAYER_IN_MLP_MAP: 2
    NUM_LAYER_IN_PRE_MLP_MAP: 1

    D_MODEL: 64
    NUM_ATTN_LAYERS: 2
    NUM_ATTN_HEAD: 2
    DROPOUT_OF_ATTN: 0.1 

    USE_LOCAL_ATTN: True