DATA_CONFIG:
    DATASET: WaymoDatasetV2
    
    dataset_info:
      data_root: '/data/waymo_open_dataset/mtr_processed_data/v1'
      split_dir: {
          'train': 'processed_scenarios_training', 
          'val': 'processed_scenarios_validation'
      }
      info_file: {
          'train': 'processed_scenarios_training_infos.pkl', 
          'val': 'processed_scenarios_val_infos.pkl'
      }
      cache_dir: {
          'train': 'v2_train_cache',
          'val': 'v2_val_cache'
      }

      object_type: ['TYPE_VEHICLE', 'TYPE_PEDESTRIAN', 'TYPE_CYCLIST']

      sample_interval: {
          'train': 1, 
          'val': 10
      }

    time_info:
      time_period_per_data: 0.1

      time_set_num: 8
      time_set_interval: 10

      time_sample_num: 5
      time_sample_interval: 2

      total_time_step: 80

    map_feature:
      polyline_point_num: 20
      polyline_subsample_interval: 4

      max_polyline_num: {
        lane: 512,
        road_line: 128,
        road_edge: 128,
        map_others: 64
      }
      feature_dim: {
        lane: 19,
        road_line: 14,
        road_edge: 8,
        map_others: 9
      }

    max_agent_num: 64

    filter_param:
      max_xy_diff: 5.0
      max_heading_diff: 0.3

    anchor_param:
      speed: [3.0, 7.0, 12.0]
      angle: [-0.3, -0.1, 0, 0.1, 0.3]

    anchor_loss_weight: {
      x: 1.0,
      y: 1.0,
      heading: 10.0,
    }

MODEL:
    model_name: PureSeqModelV2

    model_parameter:
      # map encoder
      in_polyline_dim: 64
      in_polyline_layer: 3
      in_polyline_pre_layer: 1
      between_polyline_dim: 256
      between_polyline_layer: 3
      between_polyline_pre_layer: 1

      # seq model
      seq_embedding_dim: 256
      seq_inter_dim: 1024
      seq_head: 16
      seq_layer: 6

      # loss calculation
      loss_weight: {
        x: 1.0,
        y: 1.0,
        heading: 10.0,
      }
      regression_weight: 1.0
      classification_weight: 5.0
      loss_type: 'L2'

      # normalization
      normalization_para: {
        xy: 50.0,
        heading: 1.0,
      }

      # traj generation
      traj_num: 6
      traj_trial_num: 32
      traj_init_min_dis: 1.0
      traj_iteration: 3

    data_dim:
      # Dim should match dataset, so following parameters are not free parameter. They are used only for convenience.
      lane: 19
      road_line: 14
      road_edge: 8
      map_others: 9

      ego: 30
      agent: 55

      ego_anchor: 15
      agent_anchor: 15
      anchor_num: 16

      ego_target: 15
      agent_target: 15

      points_in_polyline: 20

OPTIMIZATION:
    BATCH_SIZE_PER_GPU: 10
    NUM_EPOCHS: 30

    OPTIMIZER: AdamW
    LR: 0.0001
    WEIGHT_DECAY: 0.01

    SCHEDULER: lambdaLR
    DECAY_STEP_LIST: [3, 6, 9, 12, 15, 18, 21, 24, 27]
    LR_DECAY: 0.75
    LR_CLIP: 0.000001

    GRAD_NORM_CLIP: 1000.0
