DATA_CONFIG:
    DATASET: WaymoDatasetWayformer
    
    dataset_info:
      data_root: '/data/waymo_open_dataset/mtr_processed_data/v1'
      split_dir: {
          'train': 'processed_scenarios_training', 
          'val': 'processed_scenarios_validation'
      }
      info_file: {
          'train': 'processed_scenarios_training_infos.pkl', 
          'val': 'processed_scenarios_val_infos.pkl'
      }
      cache_dir: {
          'train': 'wayformer_train_cache',
          'val': 'wayformer_val_cache'
      }

      # object_type: ['TYPE_VEHICLE', 'TYPE_PEDESTRIAN', 'TYPE_CYCLIST']
      object_type: ['TYPE_VEHICLE']

      sample_interval: {
          'train': 1, 
          'val': 1
      }

    time_info:
      feature_time_step: 5
      feature_time_interval: 2

      target_time_step: 16
      target_time_interval: 5

      time_interval_time: 0.1

      total_time_step: 80

    map_feature:
      polyline_subsample_interval: 8

      max_polyline_num: {
        lane: 2048,
        road_line: 256,
        road_edge: 128,
        map_others: 64
      }

      feature_dim: {
        lane: 19,
        road_line: 14,
        road_edge: 8,
        map_others: 9
      }

    max_agent_num: 64
    
    filter_param:
      max_xy_diff: 5.0
      max_heading_diff: 0.3

MODEL:
    model_name: WayformerGMMModel

    model_parameter:
      # encoder parameter
      latent_seq_length: 200
      encoder_embedding_dim: 256
      encoder_inter_dim: 1024
      encoder_head: 16
      encoder_layer: 4

      # decoder parameter
      decoder_embedding_dim: 256
      decoder_inter_dim: 1024
      decoder_head: 16
      decoder_layer: 4

      dropout_rate: 0.0

      # loss parameter
      loss_weight: {
        x: 1.0,
        y: 1.0,
      }
      loss_type: 'L2'
      loss_anchor_for_choice: False
      regression_weight: 1.0
      classification_weight: 100.0

      # anchor parameter
      anchor_num: 32

    data_dim:
      # Dim should match dataset, so following parameters are not free parameter. They are used only for convenience.
      lane: 19
      road_line: 14
      road_edge: 8
      map_others: 9

      target: 14
      agent: 14

      label: 5 # x, y, std_x, std_y, rho


OPTIMIZATION:
    BATCH_SIZE_PER_GPU: 10
    NUM_EPOCHS: 30

    OPTIMIZER: AdamW
    LR: 0.0001
    WEIGHT_DECAY: 0.01

    SCHEDULER: lambdaLR
    DECAY_STEP_LIST: [2, 4, 6, 8, 10, 12, 14, 16, 18]
    LR_DECAY: 0.75
    LR_CLIP: 0.000001

    GRAD_NORM_CLIP: 1000.0
