model_parameter:
  # map encoder
  in_polyline_dim: 64
  in_polyline_layer: 3
  in_polyline_pre_layer: 1
  between_polyline_dim: 256
  between_polyline_layer: 3
  between_polyline_pre_layer: 1

  # seq model
  seq_embedding_dim: 256
  seq_inter_dim: 512
  seq_head: 16
  seq_layer: 4

data_dim:
  # Dim should match dataset, so following parameters are not free parameter. They are used only for convenience.
  lane: 19
  road_line: 14
  road_edge: 8
  map_others: 9

  agent: 30
  agent_target: 25

  time_set_num: 8
  points_in_polyline: 20




